services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spring-sec
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
